version: '2'
services:
  hotel_covid_database:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  hotel_covid_database_test:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    networks:
      - internal

  hotel_covid_backend:
    build: ../../../
    restart: on-failure
    depends_on:
      - hotel_covid_database
      - hotel_covid_database_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
      POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
    networks:
      - internal

  reverse-proxy:
    image: traefik:latest
    restart: on-failure
    networks:
      - proxy
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=pacoferre@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme

volumes:
  postgres-data:
  traefik-acme:

networks:
  internal:
  proxy:
    external: true
