version: '2'
services:
  hotel_covid_database:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  hotel_covid_database_test:
    image: postgres
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    networks:
      - internal

  hotel_covid_backend:
    build: ../../../
    ports:
    - "8080:8080"
    restart: on-failure
    depends_on:
      - hotel_covid_database
      - hotel_covid_database_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
      POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal:
