version: '2'
services:
  hotel_covid_database:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  hotel_covid_database_test:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    networks:
      - internal

  hotel_covid_backend:
    build: ../../../
    restart: on-failure
    depends_on:
      - hotel_covid_database
      - hotel_covid_database_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
      POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hotel_covid_backend.entrypoints=web"
      - "traefik.http.routers.hotel_covid_backend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.hotel_covid_backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hotel_covid_backend.middlewares=hotel_covid_backend-https-redirect"
      - "traefik.http.routers.hotel_covid_backend-secure.entrypoints=websecure"
      - "traefik.http.routers.hotel_covid_backend-secure.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.hotel_covid_backend-secure.tls=true"
      - "traefik.http.routers.hotel_covid_backend-secure.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.hotel_covid_backend-secure.service=hotel_covid_backend"
      - "traefik.http.services.hotel_covid_backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - internal

  reverse_proxy:
    image: traefik:latest
    restart: on-failure
    networks:
      - internal
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${LETSENCRYPT_NOTIFICATION_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme

volumes:
  postgres-data:
  traefik-acme:

networks:
  internal:
