version: '2'
services:
  hotel_covid_database:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: hotelcovid19
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  hotel_covid_database_test:
    image: postgres
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: hotelcovid19
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    networks:
      - internal

  hotel_covid_backend:
    build: ../../../
    ports:
    - "8080:8080"
    restart: on-failure
    depends_on:
      - hotel_covid_database
      - hotel_covid_database_test
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal: