ALTER TABLE health_records ADD COLUMN RESPIRATORY_DISTRESS BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN PHLEGM BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN SMELL_TASTE_LOSS BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN PALPITATIONS BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN DIARRHEA BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN MUSCLE_PAIN BOOLEAN NOT NULL;
ALTER TABLE health_records ADD COLUMN JOIN_PAIN BOOLEAN NOT NULL;