ALTER TABLE health_records ADD(
     RESPIRATORY_DISTRESS BOOLEAN NOT NULL,
     PHLEGM BOOLEAN NOT NULL,
     SMELL_TASTE_LOSS BOOLEAN NOT NULL,
     PALPITATIONS BOOLEAN NOT NULL,
     DIARRHEA BOOLEAN NOT NULL,
     MUSCLE_PAIN BOOLEAN NOT NULL,
     JOIN_PAIN BOOLEAN NOT NULL
);