ALTER TABLE patient ADD UNIQUE (PHONE);
ALTER TABLE patient ADD UNIQUE (PERSONAL_ID);

CREATE TABLE credentials
(
    ID              SERIAL          PRIMARY KEY NOT NULL,
    USERNAME        VARCHAR         UNIQUE,
    HASHED_PASSWORD VARCHAR         NOT NULL
);

CREATE TABLE roles
(
    ID              SERIAL          PRIMARY KEY NOT NULL,
    NAME            VARCHAR(50)     UNIQUE NOT NULL
);

CREATE TABLE credential_roles
(
    CREDENTIAL_ID     INTEGER NOT NULL,
    ROLE_ID     INTEGER NOT NULL,
    PRIMARY KEY (CREDENTIAL_ID, ROLE_ID),
    FOREIGN KEY (CREDENTIAL_ID) REFERENCES credentials(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES roles(ID)
);

ALTER TABLE patient DROP COLUMN HASHED_PASSWORD;
ALTER TABLE patient ADD COLUMN CREDENTIAL_ID INTEGER NOT NULL;
ALTER TABLE patient ADD FOREIGN KEY (CREDENTIAL_ID) REFERENCES credentials(ID);

CREATE TABLE personnel
(
    ID              SERIAL          PRIMARY KEY NOT NULL,
    PERSONAL_ID     VARCHAR         UNIQUE,
    NAME            VARCHAR(50)     NOT NULL,
    PHONE           VARCHAR(50)     UNIQUE,
    CREDENTIALS_ID  INTEGER         NOT NULL,
    FOREIGN KEY (CREDENTIALS_ID) REFERENCES credentials(ID)
);

INSERT INTO roles VALUES (1, 'ADMIN');
INSERT INTO roles VALUES (2, 'PATIENT');
INSERT INTO roles VALUES (3, 'PERSONNEL');
